networks:
  myAppNetwork:


volumes:
  bytesant_db_vol:
    driver: local
    driver_opts:
      type: none
      device: "./db_data"
      o: bind

services:
  transactions.database:
    container_name: transactions.database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStong_Password123#
    volumes:
      - bytesant_db_vol:/var/opt/mssql/data
  transactions.api:
    container_name: transactions.api
    image: ${DOCKER_REGISTRY-}transactionsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Transactions.Info.Extra.API/Dockerfile
    depends_on:
      - transactions.database
  transactions.web:
    container_name: transactions.web
    image: ${DOCKER_REGISTRY-}transactionsweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_HTTPS_PORTS=7001
    ports:
      - 8081:8080
    build:
      context: .
      dockerfile: Transactions.Info.Web/Dockerfile
    depends_on:
      - transactions.database
