FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Transactions.Info.Extra.API/Transactions.Info.Extra.API.csproj", "Transactions.Info.Extra.API/"]
RUN dotnet restore "Transactions.Info.Extra.API/Transactions.Info.Extra.API.csproj"
COPY . .
WORKDIR "/src/Transactions.Info.Extra.API"
RUN dotnet build "Transactions.Info.Extra.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Transactions.Info.Extra.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Transactions.Info.Extra.API.dll"]